# Generated by Django 6.0 on 2025-12-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='temp_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
