# Generated by Django 6.0 on 2025-12-28 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='user_id',
        ),
        migrations.AddField(
            model_name='chats',
            name='auth',
            field=models.ForeignKey(db_column='auth_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chatbotapi.auth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='chatbotapi.auth'),
        ),
    ]
