# Generated by Django 6.0 on 2025-12-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapi', '0002_auth_temp_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='temp_username',
        ),
    ]
