# Generated by Django 6.0 on 2025-12-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapi', '0003_remove_auth_temp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='temp_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
