# Generated by Django 6.0 on 2025-12-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapi', '0004_auth_temp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auth',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
