# Generated by Django 6.0 on 2025-12-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapi', '0006_auth_key_chats_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='role',
            field=models.CharField(choices=[('message_personal', 'Personal Message'), ('message_system', 'System Message'), ('message_bot', 'Bot Message')], default='message_personal', max_length=50),
        ),
    ]
