# Generated by Django 6.0 on 2025-12-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapi', '0007_alter_chats_name_alter_conversation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='auth',
            name='reset_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
